### ISSUE TITLE
TK10-5 Prueba login y registro con json-server

### ISSUE THREAD

**Issue by marioG130** [marioG130/ISPC-ProgramadorWeb-PI#124]
Se implementa funcionamiento del login y registro con datos de pueba desde un json-server, y consumiendo los datos en Angular usando un HttpClient.

- Ver comentarios commit inicial https://github.com/marioG130/ISPC-ProgramadorWeb-PI/pull/122.

**Comment by Ferchy341** [comment]
Realizado
