### ISSUE TITLE
TK22-2 Productos mostrados desde el Backend

### ISSUE THREAD

**Issue by marioG130** [marioG130/ISPC-ProgramadorWeb-PI#198]
En el frontend (dashboard de usuario), la lista de productos mostrados actualmente viene de un archivo JSON. Ahora se deben mostrar los productos que realmente están en la base de datos MySQL del backend. Por ahora se mantienen las imágenes en el subdirectorio "assets" del frontend.

**Comment by Ferchy341** [comment]
Realizado.
