### ISSUE TITLE
TK91-5 Mantenimiento esquema general BBDD

### ISSUE THREAD

**Issue by marioG130** [marioG130/ISPC-ProgramadorWeb-PI#34]
- Tareas relacionadas con el mantenimiento del esquema general de la Base de Datos.
- Generacion de código SQL para inicializar la base de datos.
- Generación de datos para las tablas durante el desarrollo del proyecto.
- Documentación de los procesos de instalación y actualización de la base de datos.

**Comment by marioG130** [comment]
Se introdujo en la rama "develop" el archivo **diagrama-DER.mdj** realizado con StarUML **5.1.0** y su exportación a imagen diagrama-DER.png.

**Comment by marioG130** [comment]
Se corrige el tipo del campo "idVenta" de INTEGER a BIGINT, porquer daba un error al momento de crear la clave foranea.

**Comment by marioG130** [comment]
Se cambió la estructura de la tabla "detalleVenta", colocando una primary-key (PK) de un solo campo. Antes tenia una PK compuesta (idVenta, idProducto), pero esta situación no es soportada por el ORM de Django. Esos dos campos se sacaron de la PK y quedaron solamente siendo FK a sus respectivas tablas.

**Comment by Ferchy341** [comment]
Realizado.
