### ISSUE TITLE
TK91-6 Instalación y mantenimiento stack Django

### ISSUE THREAD

**Issue by marioG130** [marioG130/ISPC-ProgramadorWeb-PI#35]
Tareas generales de instalación y mantenimiento del stack Django para el Backend.

**Comment by marioG130** [comment]
Una vez creada la database, se creó el modelo de datos de Django, archivo "models.py" haciendo un "inspectdb". A partir de este punto, se decide mantener de forma manual el modelo en Python, para de esta forma no perder sincronismo con lo diseñado en StarUML.

**Comment by marioG130** [comment]
- Se modificó la ubicación de "models.py" llevandolo a la app "webapi"
- Se registraron todas las clases/tablas en admin.py en el orden correcto
- Se colocó la interfaz del "admin" en castellano

**Comment by Ferchy341** [comment]
Realizado.
